### ISSUE TITLE
How can I make this work with MDsveX?

### ISSUE THREAD

**Issue by bwklein** [yuanchuan/vite-plugin-autoimport#4]
I have a SvelteKit site that uses [MDsveX](https://mdsvex.pngwn.io/docs#mdsvex) to convert Markdown files into Svelte components.

I have built a set of design components that I would like editors to use to extend the Markdown that they write.
I would like to free the editors from adding all of the import statements for every component that they want to use in their Markdown.
I found your plugin which would be perfect, but I am struggling to get it to work with my setup.

If I remove MDsveX and only use .svelte components directly, then this plugin works fine, but doesn't solve my issue.

Any help in configuring this plugin to auto-import for components in the .md files would be wonderful.

**Comment by yuanchuan** [comment]
Does this help?

``` js  
autoImport({
  /* ... */
  include: ['**/*.svelte', '**/*.md'],
});
```

**Comment by yuanchuan** [comment]
Well, I've just tested with `MDsveX`, <del> the following config seems to work: </del> 

```js
import autoImport from 'vite-plugin-autoimport';
import md from 'mdsvex';

export default {
  extensions: ['.svelte', '.md'],
  preprocess: [
    md.mdsvex({
      extensions: ['.md']
    }), 
  ],
  kit: {
    vite: {
      plugins: [
        autoImport({
          /* Include md files */
          include: ['**/*.svelte', 'src/**/*.md'],
        }),
      ],
    }
  }
}
```

(Edit)  

The `mdsvex ` processes before `auto-import` so this won't work. I'll go test if I could provide method to add it inside preprocess instead of in vite plugins

**Comment by bwklein** [comment]
That would be excellent and I think this is what was blocking me, I need the imports to happen when MDsveX is converting the markdown to Svelte components.

**Comment by bwklein** [comment]
@yuanchuan any luck?

**Comment by yuanchuan** [comment]
@bwklein I couldn't make it work last week due to the order of preprocessors. I'll try again

**Comment by bwklein** [comment]
Thank you, it will be amazing to use this with MDSveX. Reducing so much extra code from the markdown files.

**Comment by yuanchuan** [comment]
@bwklein  Please try version `1.6.1`. Now it can be used as preprocessor as well. Put it before `mdsvex`.

```js
preprocess: [
  autoImport({
    components: ['./src/lib/components'],
    include: ['**/*.(svelte|md)'],  /* search for both .svelte and .md */
  }),
  mdsvex({
    extensions: ['.md']
  })
]
```

**Comment by bwklein** [comment]
It is working!  But, only if I add an empty script element to the top of the markdown body.

`<script></script>`

If I remove that from the top of the markdown file, then I get errors for the components not defined.

Is there a way to have it work without the empty script element?

**Comment by yuanchuan** [comment]
This PR should fix it https://github.com/yuanchuan/vite-plugin-autoimport/pull/7

**Comment by yuanchuan** [comment]
I'm still testing. Might be ready in a few hours

**Comment by bwklein** [comment]
Can I invite you into a repo for testing?

**Comment by bwklein** [comment]
Seems to work sometimes without the <script> element at the top of the Markdown body.

![image](https://user-images.githubusercontent.com/12104446/164350269-4fe8fd1f-b5ac-417d-88ab-88a4528588b7.png)

**Comment by yuanchuan** [comment]
That's weird, maybe caused by the initial directory traversing.

**Comment by yuanchuan** [comment]
Should be fixed now with `1.6.2`.

**Comment by bwklein** [comment]
I am still having problems with one of the pages.
Please see this repo: https://gitlab.com/bwklein/theme-demo
You can use GitPod.io to launch the IDE and live preview online and reproduce the error.

Here is a video where I am demonstrating the issue.
https://youtu.be/IhB5Op6psEU

One thing I thought of after the video was recorded, could it be the HTML code in that 'sidebar.md' Markdown file throwing things off?

**Comment by yuanchuan** [comment]
Thank you for the video :)

It's strange that I'm unable to reproduce the error locally. 

Hmm.. How about to change the `include` value from   `['**/*.(md|svelte)']` to `['./src/**/*.(md|svelte)']`?

**Comment by bwklein** [comment]
> How about to change the include value from ['**/*.(md|svelte)'] to ['./src/**/*.(md|svelte)']?

That does not change the error when removing the `<script></script>` from the Markdown.

**Comment by yuanchuan** [comment]
Does `npm run build` expose any error after removing `<script></script>` from `sidebar.md`

**Comment by bwklein** [comment]
Not really, just more of the same not defined errors...

```
vite v2.9.5 building for production...
transforming (1) src/routes/__layout.svelte3:48:19 PM [vite-plugin-svelte] /workspace/theme-demo/src/routes/sidebar.md:11:26 'Icon' is not defined
 9: 
10: <Layout_MDSVEX_DEFAULT {...$$props} {...metadata}>
11: <h2 id="--license-prices"><Icon icon='pyrosim-results' classes='inline-block h-8'/> <Icon icon='pathfinder-results' classes='inline-block h-8'/> License Prices</h2>
                              ^
12: <p>PyroSim is available under two license models:
13: A standard perpetual license (including one year of free support and upgrades), or a yearly subscription license.
```

**Comment by yuanchuan** [comment]
May I see the version number in `node_modules/vite-plugin-autoimport/package.json`, just need to confirm

**Comment by bwklein** [comment]
![image](https://user-images.githubusercontent.com/12104446/164502592-3edf926f-3676-4cc4-a353-eae445b830c4.png)

**Comment by yuanchuan** [comment]
Alright! I've just tested it on both MacOS and WIndows. Still can't reproduce it...

**Comment by bwklein** [comment]
Can you try using the GitPod Environment to test it?  Or, would you like to jump into a Zoom call with me to dig around?

**Comment by yuanchuan** [comment]
Yeah! Now I see the error with GitPod Environment. Let me check it out first

**Comment by yuanchuan** [comment]
Fixed! Please try `1.6.3`

**Comment by bwklein** [comment]
1.6.3 works!!!! AWESOME!  Thank you!

**Comment by yuanchuan** [comment]
Closing it by now. Please reopen it if there are other issues. Cheers!

**Comment by leokeba** [comment]
Hello, thanks for the good work, this has been really useful for me, and it works quite well. However, I found a little bug : 

When a markdown file ends with a list element (line starting with a '-'), it breaks the auto-import functionality and triggers an error when trying to build with vite.

Maybe there are other similar edge-cases, but this is the one I found and it happened consistently, took me a while to figure out the origin. Anyway, It seems I cannot reopen this issue my myself, but I thought it would make more sense posting here rather than opening a new one.

Cheers

**Comment by yuanchuan** [comment]
@leokeba 

I can't reproduce it. Check out https://stackblitz.com/edit/vitejs-vite-tfpzge?file=src%2Froutes%2Fmdx%2F%2Bpage.md

**Comment by leokeba** [comment]
Hello @yuanchuan, thanks for looking into it. I found a way to reproduce it on stackblitz, but doing so also helped me find the real fix. The issue seems to stem for the fact that I had defined autoimport as a preprocessor in svelte config instead of a plugin in vite config. That does not seem the right way to do things and frankly I'm suprised that it worked, but I moved back to its expected location and the bug does not appear anymore.

If you are still curious about the bug anyway, here's a way to reproduce it : https://stackblitz.com/edit/vitejs-vite-oeayvc?file=src/routes/mdx/+page.md

**Comment by leokeba** [comment]
One last follow-up detail : 
After removing autoimport from svelte.config.js and adding it into vite.config.js, I get warnings in VSCode because of "undefined components". It still works in the end, but to remove the warnings I have to configure it in both places, is that the right way to go ? Seems a bit sketchy, but the warnings are very annoying so I will leave it like that for now.

**Comment by yuanchuan** [comment]
@leokeba Fixed in `1.6.10` :)

**Comment by leokeba** [comment]
Indeed it works, thanks being so quick :)

So just to clarify, what is the recommended workflow, svelte preprocessor or vite plugin ? Is there any downsides/upsides to either ? I mean except for the intellisense stuff obviously.

**Comment by yuanchuan** [comment]
Using Vite plugin will detect new created components while the preprocessor does not, so you need to restart the dev server to recognize them. I personally use Vite plugin since I don't use VSCode.
